name: Deploy to Amazon EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Inventory Service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest ./inventory-service
          docker push ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest

      - name: Build and push Order Service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest ./order-service
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest
